import request from 'supertest';
import app from '../index.js';

describe('Tickets', () => {
  it('employee sees only own tickets', async () => {
    const res = await request(app)
      .get('/api/tickets')
      .set('x-user-id', '2')
      .set('x-user-role', 'EMPLOYEE');
    expect(res.status).toBe(200);
    expect(Array.isArray(res.body.tickets)).toBe(true);
    // Ensure all tickets belong to employee 2
    for (const t of res.body.tickets) {
      expect(t.created_by).toBe(2);
    }
  });

  it('admin can update a ticket priority', async () => {
    // Create a new ticket as employee 2 first
    const created = await request(app)
      .post('/api/tickets')
      .set('x-user-id', '2')
      .set('x-user-role', 'EMPLOYEE')
      .send({ title: 'Test Ticket', description: 'Generated by test' });
    expect(created.status).toBe(201);

    const ticketId = created.body.ticket.id;
    const res = await request(app)
      .put(`/api/tickets/${ticketId}`)
      .set('x-user-id', '1')
      .set('x-user-role', 'ADMIN')
      .send({ priority: 'CRITICAL' });
    expect(res.status).toBe(200);
    expect(res.body.ticket.priority).toBe('CRITICAL');
  });
});
